# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: About
    url: /about/
    weight: 5
  - name: Work
    url: /#projects
    weight: 10
  - name: Capstone
    url: /capstone/
    weight: 15
  - name: Writing
    url: /#blog
    weight: 20
  - name: Contact
    url: /#contact
    weight: 30
